version: '3.8'
services:
  fdp:
    command: gunicorn -b 0.0.0.0:80 "fdp.fdp:create_app('0.0.0.0', 80, 'http://virtuoso:8890/sparql')"
    ports:
      - 80:80
  fdpsearch:
    environment:
      - GRLC_SERVER_NAME=0.0.0.0:8088